Flirt.delete_all

Flirt.create!([
  {message: "I'd dice you up and have you for dinner ;)", opening_line: false, suggested: true, tweet_id: "571462631451598848", sent_before: false},
  {message: "Darling! It's me, Freddie T. Remember our summer at gay camp?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Please stop sending me private messages telling me you want to 'bum' me...I have a boyfriend, and he is hot diggedy damn!!", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "How are you still single? Wanna mingle?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Shwing! My gaydar is off the scale playa!!!", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Look at us, we are just like the Sex and the City girls", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Do you mix concrete for a living? Because you're making me hard ", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Honey you can’t knock it until you try it", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "I'm very good at keeping secrets ;-) just FYI", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "You're so cute when you're angry and stupid.  Oh mama!", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "You're a double gay. No returnsies!", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "I don't know what makes you so stupid, but it really works!", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "What did you have for breakfast? Bitch Flakes?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Hey, that was quite a mouthful, but I guess you're used to that sort of thing", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Hey man, into new things?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Fuck me if I'm wrong, but is your name Easy Bottom?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Hey, do you work out? What's your secret?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Your insecurity turns me on so bad", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "When I first heard there was a film called Whiplash, I thought it was going to be about a bogus insurance claim gone awry", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "You could do some sexy things with that anger.  I'm thinking about it now....stop it!", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Your body is 65% water and I'm thirsty", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "I don't have a library card, but do you mind if I check you out?", opening_line: true, suggested: true, tweet_id: "571147314934390786", sent_before: false},
  {message: "If you walked in to a gay bar would you feel a dick?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Hehehehe.  Stop it...no keep going.", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "I love your outdated opinions - it's like you're straight out of 1950, and the 50s were fab-you-lous", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "I know you are but what am I?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "So I'm responding to your gay ad in the gay times - how can I be of service?", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "You are adorable. I just want to cover you in spinkles and buy you presents", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Isn't this fun?", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "This is so us", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Don't hate. Educate.", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "You are so naughty.  And I like it", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "PILLOW FIGHT!!!!", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "You are smoking hot baby! Tssssss......", opening_line: true, suggested: false, tweet_id: nil, sent_before: false},
  {message: "Tease me some more.  This is fun!", opening_line: false, suggested: false, tweet_id: nil, sent_before: false},
  {message: "I never knew I could be so turned on by a bad boy", opening_line: false, suggested: true, tweet_id: "571481940190089216", sent_before: false},
  {message: "How much do you bench cutie?", opening_line: true, suggested: false, tweet_id: nil, sent_before: true},
  {message: "What's your star sign?  Leo?...Cancer?...don't tell me...Gemini?  Ok tell me :)", opening_line: true, suggested: false, tweet_id: nil, sent_before: true},
  {message: "Hey trouble.  Do you still have my Kylie CD - I want it back, you're so naughty!", opening_line: true, suggested: false, tweet_id: nil, sent_before: false}
])
